---
language: java
script: ./gradlew
jdk:
  - oraclejdk7
  
language: android
android:
  components:
    # The BuildTools version used by project
    - build-tools-23.0.0

    # The SDK version used to compile project
    - android-23

before_install:
 - chmod +x gradlew